Repository apache/shardingsphere-ui, pull requests merged in 2020-11, with the labels that each got.

#27 Fixes dependencies
  shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/servcie/impl/GovernanceServiceImpl.java
  shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/util/ConfigurationYamlConverter.java
Labels: refactor

#29 update ui dependencies licenses
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/LICENSE
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-antlr4-runtime.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-axios.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-echarts-liquidfill.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-element-ui.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-incubator-echarts.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-jline.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-js-yaml.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-lodash.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-moment.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-normalize.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-protobuf-java.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-resize-detector.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-vue-i18n.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-vue-router.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-vue.txt
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-vuex.txt
Labels: type: build

#64 Update release notes
  RELEASE-NOTES.md
Labels: release

#66 adjust script lineEnding in binary assembly
  shardingsphere-ui-distribution/shardingsphere-ui-bin-distribution/src/main/assembly/shardingsphere-ui-bin-distribution.xml
Labels: type: build

#67 Refactor registry center structure
  shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/servcie/impl/ShardingSchemaServiceImpl.java
Labels: type: refactor

#68 update dependencies
  pom.xml
  shardingsphere-ui-backend/pom.xml
Labels: type: refactor

#69 Revert code for 5.0.0-alpha
  pom.xml
  shardingsphere-ui-backend/pom.xml
  shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/servcie/impl/ShardingSchemaServiceImpl.java
Labels: type: refactor
